name: CI

on: [push, pull_request]

jobs:

  build:
    name: Build

    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.14.x, 1.15.x]

    runs-on: ${{ matrix.platform }}
      
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Test
      run: make unit

    - name: Lint
      env:
        GOPATH: /home/runner/work/
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        make lint
